### ISSUE TITLE
The discarded cards are not reshuffled into the deck after it is emptied

### ISSUE THREAD

**Issue by Deriboy** [cs340tabyu/CS340Summer2017#41] opened 2017-08-04 18:01 UTC

**Comment by sonofafinch** [comment] 2017-08-06 04:36
![screenshot_1501994130](https://user-images.githubusercontent.com/14119659/29000638-791ae040-7a2e-11e7-87d0-f64c0603b7d5.png)

Currently, it's looking like this is an issue with the server's board model and its shuffle algorithm. Still testing.

**Comment by sonofafinch** [comment] 2017-08-06 05:13
The issue was caused by a shallow copy of a local variable during shuffling. Should be fixed based on testing. However, the negative values on the client still occur until a person's turn comes around. Looking into that now.

**Comment by sonofafinch** [comment] 2017-08-07 16:29
Negative values should be fixed.

**Closed as completed by sonofafinch** 2017-08-07 16:29 UTC
Labels: P2: Halts Gameplay, Resolved, Team FYSH
